/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capabilities
         * @description Which filters and orders the configured template backend can honour.
         *
         *     ``orderBy.*`` keys report which fields ``GET /templates`` can sort by. They default
         *     to false, so a backend that cannot sort reports nothing orderable and a client should
         *     offer no sortable columns. See ``capabilities.py``.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_get_capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List templates matching the filters -- one row per key by default.
         *
         *     A row in the store is a *version*, so an unfiltered read of the seam returns a key once
         *     per version it has ever had. ``mostRecentActiveVersion`` defaults to ``true`` and asks
         *     the backend for the current version of each key instead: the highest-numbered ``active``
         *     or ``draft`` one. The collapsing happens in the store, not here, so a page is still a
         *     page of what the backend counted.
         *
         *     Send ``mostRecentActiveVersion=false`` for the raw listing, every version included. A
         *     backend that cannot answer the filter has it dropped like any other unsupported one, and
         *     then returns every version too.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_list_templates"];
        put?: never;
        /**
         * Create Template
         * @description Create a template's first version.
         *
         *     Whether re-using an existing key is an error is the backend's call, not this API's --
         *     the seam does not define it, and a backend that treats a repeat ``create_template`` as
         *     a new version is behaving legitimately. Use ``POST /templates/{key}/versions`` when you
         *     mean "next version of this key".
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_create_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Template Versions
         * @description Every version of one template, newest version first.
         *
         *     The service resolves this by filtering on the key, which matches nothing for a key that
         *     does not exist rather than raising -- so an empty result is a missing key, and is
         *     reported as the 404 the contract documents rather than an empty list. A key that exists
         *     always has at least one version.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_list_template_versions"];
        put?: never;
        /**
         * Create Template Version
         * @description Create a new version of an existing template, copied forward from its latest one.
         *
         *     Templates are versioned rather than edited in place, which is why this is a POST that
         *     creates a resource and not a PATCH that mutates one: an already-published version is
         *     never modified. Fields left unset are carried over from the latest version.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_create_template_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template Version */
        get: operations["vintasend_templates_management_api_templates_manager_api_get_template_version"];
        put?: never;
        post?: never;
        /** Delete Template Version */
        delete: operations["vintasend_templates_management_api_templates_manager_api_delete_template_version"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/composition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template Composition
         * @description One version assembled the way the template engine will receive it.
         *
         *     A managed template can build on another: ``{% managed_extends "base" %}`` to fill a
         *     base's ``{% managed_children %}`` hole and override its ``{% managed_block %}`` regions,
         *     ``{% managed_include "footer" %}`` to splice a fragment in. All of it is resolved before
         *     the engine runs, so the stored ``bodyTemplate`` is only half the template -- this is what
         *     actually renders.
         *
         *     Nothing here is rendered against a context: engine syntax survives untouched. Use
         *     ``POST /templates/{key}/preview`` for the rendered result.
         *
         *     Also reports what this version directly references, and whether it is abstract --
         *     recomputed from the source rather than read from the stored flag, so it is the authority
         *     behind the ``isAbstract`` on every template payload.
         *
         *     A template that cannot be assembled -- a base that does not exist, a chain that loops, a
         *     malformed tag -- comes back as a 409 ``TEMPLATE_COMPOSITION_ERROR`` naming the chain that
         *     broke, for the same reason a template that will not render is a 409 rather than a 500.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_get_template_composition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status History
         * @description The status audit trail, most recent change first.
         *
         *     Omitting ``version`` asks for the whole key's history, which backends that keep it that
         *     way will return. Unlike everywhere else in this API, ``version=None`` here does not mean
         *     "the latest version".
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_get_status_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Template Status
         * @description Move one version to an explicitly named status.
         *
         *     Setting a version to the status it already holds is a no-op the service reports as
         *     success: the version comes back unchanged and no audit entry is written, so a client
         *     retrying a request does not fill the trail with entries recording nothing.
         *
         *     A move the lifecycle does not allow is a 409 with code ``INVALID_STATUS_TRANSITION``.
         *     ``allowedTransitions`` on every template payload says in advance which moves will work.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_set_template_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Template
         * @description Publish one version.
         *
         *     Other versions of the same key that are already active are left alone: a key may hold
         *     several active versions at once, and choosing between them is the host application's
         *     call, not this API's.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_activate_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate Template
         * @description Retire one version without archiving it, so it can be activated again later.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_deactivate_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Template
         * @description Archive one version. Terminal under the default lifecycle: an archived version has
         *     no allowed transitions, and publishing a new version is the way forward from there.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_archive_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Template
         * @description Render a version against a supplied context, whatever its status.
         *
         *     Pinning ``version`` is the point: it is what lets a draft be reviewed before anyone
         *     activates it. Omitting it previews the latest version.
         *
         *     A template that fails to render comes back as a 409 ``PREVIEW_UNAVAILABLE`` carrying the
         *     renderer's message, because a broken template is what the caller asked to find out.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_preview_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Template Tags
         * @description Replace one version's tags, creating any tag that does not exist yet.
         *
         *     A PUT that edits a version in place, unlike every other write on a template -- which
         *     creates a version instead. Tags describe how a template is *found*, not what it renders,
         *     so relabelling one should not fork a version and drop it back to draft. To change the
         *     tags *and* the content together, send them on ``POST /templates/{key}/versions``.
         *
         *     An empty ``tags`` list clears the version's tags. Omitting ``version`` retags the latest.
         */
        put: operations["vintasend_templates_management_api_templates_manager_api_set_template_tags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description List tags, newest filter first: by status, by a text search, or by tenant.
         *
         *     A tag picker wants ``?status=active``: archived tags are still attached to the templates
         *     carrying them and can still be filtered on, they are simply no longer offered.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_list_tags"];
        put?: never;
        /**
         * Create Tag
         * @description Define a tag ahead of any template using it.
         *
         *     Tagging a template creates missing tags on its own, so this is for the case where a
         *     collision with an existing tag is worth hearing about -- it is a 409 here, where tagging
         *     a template would silently resolve to the tag already there.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_create_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tag
         * @description One tag. The path accepts the tag's slug or the text it was created from.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_get_tag"];
        put?: never;
        post?: never;
        /**
         * Delete Tag
         * @description Delete a tag, removing the label from every template carrying it.
         *
         *     Not reversible, and the templates lose the label. Archive instead when the tag should
         *     stop being offered but the templates should keep it.
         */
        delete: operations["vintasend_templates_management_api_templates_manager_api_delete_tag"];
        options?: never;
        head?: never;
        /**
         * Update Tag
         * @description Rename a tag. Its slug is regenerated, so its URL changes.
         *
         *     The templates carrying the tag keep it, but a stored filter naming the old slug stops
         *     matching -- read ``slug`` off the response and store that. Renaming a tag onto another
         *     tag's text is allowed and yields a ``-2`` suffix: two tags may legitimately read the
         *     same, and the slug is what tells them apart.
         */
        patch: operations["vintasend_templates_management_api_templates_manager_api_update_tag"];
        trace?: never;
    };
    "/api/v1/tags/{slug}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Tag
         * @description Retire a tag from the pickers without touching the templates carrying it.
         *
         *     Filtering by an archived tag still returns those templates -- archiving hides the tag
         *     from ``?status=active``, it does not hide the templates.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_archive_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{slug}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Tag
         * @description Put an archived tag back on offer.
         *
         *     Unlike an archived template version -- terminal, because reviving one would rewrite what
         *     its audit trail says happened -- a tag carries no history to contradict, so archiving one
         *     is reversible.
         */
        post: operations["vintasend_templates_management_api_templates_manager_api_restore_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description One version of a template. Omitting ``version`` returns the latest.
         */
        get: operations["vintasend_templates_management_api_templates_manager_api_get_template"];
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description Delete one version of a template, or its latest version when ``version`` is omitted.
         *
         *     This deletes a *version*, never a whole key: the seam has no operation that removes
         *     every version at once, and doing it here as a loop would be a multi-step deletion with
         *     no transaction around it.
         */
        delete: operations["vintasend_templates_management_api_templates_manager_api_delete_template"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["vintasend_templates_management_api_templates_manager_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DataResponse[dict[str, bool]] */
        DataResponse_dict_str__bool__: {
            /** Data */
            data: {
                [key: string]: boolean;
            };
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "BAD_REQUEST" | "UNAUTHORIZED" | "NOT_FOUND" | "CONFLICT" | "INVALID_STATUS_TRANSITION" | "PREVIEW_UNAVAILABLE" | "TEMPLATE_COMPOSITION_ERROR" | "INTERNAL_ERROR";
            /** Message */
            message: string;
            details?: components["schemas"]["JsonValue"] | null;
        };
        /**
         * ApiErrorResponse
         * @description Error envelope returned with every non-2xx response.
         */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        JsonValue: unknown;
        /**
         * TemplateListQuery
         * @description Filters accepted by ``GET /api/v1/templates``.
         *
         *     Every filter present is combined with AND, which is what a bare field filter means in
         *     the library's filter vocabulary.
         *
         *     ``mostRecentActiveVersion`` is the one filter that is on unless a client turns it off,
         *     and the one whose default changes what a bare ``GET /templates`` returns: one row per
         *     key instead of one per version.
         *
         *     ``orderByField`` and ``orderByDirection`` have no default: most backends can order by
         *     nothing, so a default would make the common listing a 400 against them. Omitted asks for
         *     the backend own order. An order the backend cannot apply is a 400 rather than a silent
         *     drop -- unlike a dropped filter, a dropped order leaves no trace in the rows.
         */
        TemplateListQuery: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Pagesize
             * @default 20
             */
            pageSize: number;
            /** Key */
            key?: string | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Templatemanagedbackend */
            templateManagedBackend?: string | null;
            /** Version */
            version?: number | null;
            /** Status */
            status?: ("draft" | "active" | "inactive" | "archived")[] | null;
            /** Createdatfrom */
            createdAtFrom?: string | null;
            /** Createdatto */
            createdAtTo?: string | null;
            /** Updatedatfrom */
            updatedAtFrom?: string | null;
            /** Updatedatto */
            updatedAtTo?: string | null;
            /** Includesalltags */
            includesAllTags?: string[] | null;
            /** Includesanyoftags */
            includesAnyOfTags?: string[] | null;
            /**
             * Mostrecentactiveversion
             * @default true
             */
            mostRecentActiveVersion: boolean;
            /** Isabstract */
            isAbstract?: boolean | null;
            /** Orderbyfield */
            orderByField?: ("key" | "name" | "version" | "status" | "createdAt" | "updatedAt") | null;
            /** Orderbydirection */
            orderByDirection?: ("asc" | "desc") | null;
        };
        /**
         * ManagedTemplateOut
         * @description One version of a managed template.
         *
         *     Templates are versioned rather than edited in place, so this is always a specific
         *     version of ``key`` -- never "the template" in the abstract.
         */
        ManagedTemplateOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Templatemanagedbackend */
            templateManagedBackend: string;
            /** Bodytemplate */
            bodyTemplate: string;
            /** Subjecttemplate */
            subjectTemplate: string | null;
            /** Preheadertemplate */
            preheaderTemplate: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "inactive" | "archived";
            /** Tenant */
            tenant: string | null;
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            /** Tags */
            tags: components["schemas"]["ManagedTemplateTagOut"][];
            /** Allowedtransitions */
            allowedTransitions: ("draft" | "active" | "inactive" | "archived")[];
            /** Isabstract */
            isAbstract: boolean;
        };
        /**
         * ManagedTemplateTagOut
         * @description A label attached to any number of template versions.
         *
         *     ``slug`` is the tag's identity: it is normalized from ``text``, unique store-wide, and
         *     what the ``includesAllTags`` / ``includesAnyOfTags`` filters match on. A client that
         *     stores a tag reference should store the slug, and re-read it after a rename -- editing
         *     ``text`` regenerates the slug, so the old one stops matching.
         */
        ManagedTemplateTagOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /** Tenant */
            tenant: string | null;
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
        };
        /** PaginatedResponse[ManagedTemplateOut] */
        PaginatedResponse_ManagedTemplateOut_: {
            /** Data */
            data: components["schemas"]["ManagedTemplateOut"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Hasmore */
            hasMore: boolean;
        };
        /** DataResponse[ManagedTemplateOut] */
        DataResponse_ManagedTemplateOut_: {
            data: components["schemas"]["ManagedTemplateOut"];
        };
        /**
         * CreateTemplateBody
         * @description Body of ``POST /api/v1/templates``, which creates a template's first version.
         */
        CreateTemplateBody: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Templatemanagedbackend */
            templateManagedBackend: string;
            /** Bodytemplate */
            bodyTemplate: string;
            /** Subjecttemplate */
            subjectTemplate?: string | null;
            /** Preheadertemplate */
            preheaderTemplate?: string | null;
            /** Tenant */
            tenant?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ListResponse[ManagedTemplateOut] */
        ListResponse_ManagedTemplateOut_: {
            /** Data */
            data: components["schemas"]["ManagedTemplateOut"][];
        };
        /**
         * CreateVersionBody
         * @description Body of ``POST /api/v1/templates/{key}/versions``.
         *
         *     Every field is optional and ``None`` means "carry this one forward": the backend copies
         *     the latest version and applies only the fields that are set. That is why there is no
         *     ``templateManagedBackend`` or ``tenant`` here -- ``ManagedTemplateUpdateInput`` carries
         *     neither, so neither can change across versions of one key.
         *
         *     A body with nothing set is accepted and produces a new version identical to the latest,
         *     which is a legitimate way to branch a version off for a status change.
         */
        CreateVersionBody: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Bodytemplate */
            bodyTemplate?: string | null;
            /** Subjecttemplate */
            subjectTemplate?: string | null;
            /** Preheadertemplate */
            preheaderTemplate?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * VersionQuery
         * @description ``version`` on an endpoint that acts on the latest version when it is omitted.
         *
         *     ``None`` is not "no version" in the sense of "all versions" -- it is the service's
         *     documented shorthand for "the latest one", and every route that takes this passes it
         *     through unchanged.
         */
        VersionQuery: {
            /** Version */
            version?: number | null;
        };
        /** DataResponse[TemplateCompositionOut] */
        DataResponse_TemplateCompositionOut_: {
            data: components["schemas"]["TemplateCompositionOut"];
        };
        /**
         * TemplateCompositionOut
         * @description A template version assembled the way the engine will receive it.
         *
         *     Composition is resolved before any template engine runs: a version that extends a base
         *     or includes a fragment reaches the engine as one flat string with no ``managed_*`` tag
         *     left in it. The stored sources on ``ManagedTemplateOut`` are what someone typed; these
         *     are what actually renders.
         *
         *     Nothing here is rendered against a context -- ``{{ name }}`` and every other engine tag
         *     survives untouched. Use ``POST /templates/{key}/preview`` to see the rendered result.
         */
        TemplateCompositionOut: {
            /** Key */
            key: string;
            /** Version */
            version: number;
            /** Isabstract */
            isAbstract: boolean;
            /** References */
            references: components["schemas"]["TemplateReferenceOut"][];
            /** Composedbodytemplate */
            composedBodyTemplate: string;
            /** Composedsubjecttemplate */
            composedSubjectTemplate: string | null;
            /** Composedpreheadertemplate */
            composedPreheaderTemplate: string | null;
        };
        /**
         * TemplateReferenceOut
         * @description One template this version directly extends or includes.
         *
         *     Direct references only -- what the referenced templates themselves reference is not
         *     followed. ``version`` is null when the reference names no version, which resolves to
         *     whatever that key currently is at render time.
         */
        TemplateReferenceOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "extends" | "include";
            /** Key */
            key: string;
            /** Version */
            version: number | null;
            /**
             * Field
             * @enum {string}
             */
            field: "bodyTemplate" | "subjectTemplate" | "preheaderTemplate";
        };
        /**
         * StatusHistoryQuery
         * @description ``version`` on the status-history endpoint, where omitting it means every version.
         *
         *     This is the one place ``version=None`` does *not* mean "the latest": the service
         *     forwards it to the backend, which returns the whole key's history when the backend
         *     supports it.
         */
        StatusHistoryQuery: {
            /** Version */
            version?: number | null;
        };
        /** ListResponse[TemplateStatusHistoryOut] */
        ListResponse_TemplateStatusHistoryOut_: {
            /** Data */
            data: components["schemas"]["TemplateStatusHistoryOut"][];
        };
        /**
         * TemplateStatusHistoryOut
         * @description One entry in a template version's status audit trail.
         */
        TemplateStatusHistoryOut: {
            /** Templatekey */
            templateKey: string;
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "inactive" | "archived";
            /** Changedby */
            changedBy: string | null;
            /** Tenant */
            tenant: string | null;
            /** Createdat */
            createdAt: string | null;
        };
        /**
         * SetStatusBody
         * @description Body of ``POST /api/v1/templates/{key}/status``, which names the target status.
         */
        SetStatusBody: {
            /** Version */
            version?: number | null;
            /** Changedby */
            changedBy?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "inactive" | "archived";
        };
        /**
         * StatusChangeBody
         * @description Body of the named lifecycle routes (activate / deactivate / archive).
         */
        StatusChangeBody: {
            /** Version */
            version?: number | null;
            /** Changedby */
            changedBy?: string | null;
        };
        /** DataResponse[TemplatePreviewOut] */
        DataResponse_TemplatePreviewOut_: {
            data: components["schemas"]["TemplatePreviewOut"];
        };
        /**
         * TemplatePreviewOut
         * @description A template version rendered against a caller-supplied context.
         *
         *     ``renderedSubject`` and ``renderedPreheader`` are ``null`` for renderers that do not
         *     produce them -- an SMS renderer produces a body only.
         */
        TemplatePreviewOut: {
            /** Key */
            key: string;
            /** Version */
            version: number;
            /** Renderedbody */
            renderedBody: string;
            /** Renderedsubject */
            renderedSubject: string | null;
            /** Renderedpreheader */
            renderedPreheader: string | null;
        };
        /**
         * PreviewBody
         * @description Body of ``POST /api/v1/templates/{key}/preview``.
         *
         *     ``context`` is rendered verbatim. Nothing is generated: this API has no notification to
         *     resolve a registered context generator from, and a preview is meant to show what a
         *     given context produces.
         */
        PreviewBody: {
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Version */
            version?: number | null;
        };
        /**
         * SetTemplateTagsBody
         * @description Body of ``PUT /api/v1/templates/{key}/tags``, which retags a version in place.
         *
         *     An empty list is how a version's tags are cleared, so unlike the filters this one does
         *     not reject it.
         */
        SetTemplateTagsBody: {
            /** Tags */
            tags?: string[];
            /** Version */
            version?: number | null;
        };
        /**
         * TagListQuery
         * @description Filters accepted by ``GET /api/v1/tags``.
         */
        TagListQuery: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Pagesize
             * @default 20
             */
            pageSize: number;
            /** Status */
            status?: ("active" | "archived")[] | null;
            /** Search */
            search?: string | null;
            /** Tenant */
            tenant?: string | null;
        };
        /** PaginatedResponse[ManagedTemplateTagOut] */
        PaginatedResponse_ManagedTemplateTagOut_: {
            /** Data */
            data: components["schemas"]["ManagedTemplateTagOut"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Hasmore */
            hasMore: boolean;
        };
        /** DataResponse[ManagedTemplateTagOut] */
        DataResponse_ManagedTemplateTagOut_: {
            data: components["schemas"]["ManagedTemplateTagOut"];
        };
        /**
         * CreateTagBody
         * @description Body of ``POST /api/v1/tags``.
         *
         *     The slug is derived from ``text`` by the library and is not a client's to set: it is the
         *     tag's identity, and a client-supplied one could name a tag no other caller would produce.
         */
        CreateTagBody: {
            /** Text */
            text: string;
            /** Tenant */
            tenant?: string | null;
        };
        /**
         * UpdateTagBody
         * @description Body of ``PATCH /api/v1/tags/{slug}``, which renames a tag.
         *
         *     The slug is regenerated from the new text, so the tag's URL changes and a stored filter
         *     naming the old slug stops matching. The templates carrying the tag keep it.
         */
        UpdateTagBody: {
            /** Text */
            text: string;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Apiversion
             * @default v1
             */
            apiVersion: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    vintasend_templates_management_api_templates_manager_api_get_capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_dict_str__bool__"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_list_templates: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                key?: string | null;
                name?: string | null;
                description?: string | null;
                templateManagedBackend?: string | null;
                version?: number | null;
                status?: ("draft" | "active" | "inactive" | "archived")[] | null;
                createdAtFrom?: string | null;
                createdAtTo?: string | null;
                updatedAtFrom?: string | null;
                updatedAtTo?: string | null;
                includesAllTags?: string[] | null;
                includesAnyOfTags?: string[] | null;
                mostRecentActiveVersion?: boolean;
                isAbstract?: boolean | null;
                orderByField?: ("key" | "name" | "version" | "status" | "createdAt" | "updatedAt") | null;
                orderByDirection?: ("asc" | "desc") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_create_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_list_template_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_create_template_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_get_template_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_delete_template_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_get_template_composition: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_TemplateCompositionOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_get_status_history: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_TemplateStatusHistoryOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_set_template_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_activate_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusChangeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_deactivate_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusChangeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_archive_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusChangeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_preview_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PreviewBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_TemplatePreviewOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_set_template_tags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTemplateTagsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_list_tags: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: ("active" | "archived")[] | null;
                search?: string | null;
                tenant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ManagedTemplateTagOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_create_tag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateTagOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_get_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateTagOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_delete_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_update_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateTagOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_archive_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateTagOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_restore_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateTagOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_get_template: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ManagedTemplateOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_delete_template: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    vintasend_templates_management_api_templates_manager_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
